I name: Run Insta-Bot

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  insta:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.10"
      
      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install portaudio19-dev python3-dev libsndfile1
          python3 -m pip install --upgrade pip
          python3 -m pip install pyaudio
          python3 -m pip install discord.py[voice]

      - name: Execute insta-bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          if [[ -n "$BOT_TOKEN" ]]; then
            python3 src/insta.py
          fi
      